# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-30 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PinnedLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u5834\u6240\u540d')),
                ('lat', models.FloatField(verbose_name='\u7def\u5ea6')),
                ('lng', models.FloatField(verbose_name='\u7d4c\u5ea6')),
            ],
        ),
    ]
